import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:5173/signin');
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('testProvider');
  await page.getByRole('textbox', { name: 'Username' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('kohei0099');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByText('New Grant Program for Test').click();
  await page.getByRole('button', { name: 'Description' }).click();
  await page.getByRole('button', { name: 'Grant Amount' }).click();
  await page.getByRole('button', { name: 'Schedule' }).click();
  await page.locator('#applicationStartDate-day').getByText('Day').click();
  await page.getByText('1', { exact: true }).click();
  await page.locator('#applicationStartDate-month').click();
  await page.getByText('September').click();
  await page.locator('#applicationEndDate-day').getByText('Day').click();
  await page.getByRole('option', { name: '2', exact: true }).click();
  await page.locator('#applicationEndDate-month').getByText('Month').click();
  await page.getByRole('option', { name: 'September' }).locator('span').click();
  await page.locator('#decisionDate-day').click();
  await page.getByRole('option', { name: '3', exact: true }).click();
  await page.locator('#decisionDate-month').click();
  await page.getByRole('option', { name: 'September' }).locator('span').click();
  await page.getByText('Day▼').click();
  await page.getByText('4', { exact: true }).click();
  await page.getByText('Month').click();
  await page.getByRole('option', { name: 'September' }).click();
  await page.getByRole('button', { name: 'Save Schedule' }).click();
  await page.getByRole('button', { name: 'University Degree' }).click();
  await page.getByRole('button', { name: 'University Degree' }).nth(1).click();
  await page.getByRole('textbox', { name: 'What is the name of the' }).click();
  await page.getByRole('textbox', { name: 'What is the name of the' }).fill('glasgow');
  await page.locator('input[name="Degree Name"]').click();
  await page.locator('input[name="Degree Name"]').fill('computer');
  await page.locator('div').filter({ hasText: /^Condition\*equals▼What is your Degree Name\?$/ }).getByLabel('Condition*').click();
  await page.getByRole('option', { name: 'contains' }).click();
  await page.locator('input[name="Degree Name"]').click();
  await page.getByRole('combobox', { name: 'what is your degree category' }).click();
  await page.getByText('Computer Science &').click();
  await page.getByRole('main').locator('div').filter({ hasText: 'What is the name of the university you attendCondition*equals▼What is the name' }).nth(3).click();
  await page.getByText('Computer Science &').click();
  await page.getByRole('option', { name: 'Engineering' }).click();
  await page.getByText('what is your degree categoryCondition*in_list▼what is your degree').click();
  await page.getByRole('main').locator('div').filter({ hasText: 'What is the name of the university you attendCondition*equals▼What is the name' }).nth(3).click();
  await page.getByRole('button', { name: 'Remove Creative Arts & Design' }).click();
  await page.locator('[id="687e783a9f95b83462fe31e7-operator"] > .custom-select__value').click();
  await page.getByRole('option', { name: 'in_list' }).locator('span').click();
  await page.locator('input[name="What is the Degree Level"]').click();
  await page.getByRole('option', { name: 'Bachelor' }).click();
  await page.getByRole('option', { name: 'Master' }).click();
  await page.locator('div').filter({ hasText: /^Condition\*equals▼What is your grade\?▼$/ }).locator('span').nth(1).click();
  await page.getByRole('option', { name: 'in_list' }).locator('span').click();
  await page.locator('input[name="Grade for the Degree"]').click();
  await page.getByText('first class').click();
  await page.getByRole('option', { name: 'upper second class' }).click();
  await page.locator('div').filter({ hasText: /^Condition\*equals▼Is your degree honours\?▼$/ }).locator('span').nth(1).click();
  await page.locator('input[name="Honours"]').click();
  await page.locator('[id="687e76b39f95b83462fe31cc-operator"] > .custom-select__value').click();
  await page.getByRole('option', { name: 'in_list' }).locator('span').click();
  await page.locator('input[name="Honours"]').click();
  await page.getByRole('option', { name: 'Yes' }).click();
  await page.getByRole('option', { name: 'No' }).click();
  await page.locator('div').filter({ hasText: /^Condition\*equals▼What is your degree status\?▼$/ }).getByLabel('Condition*').click();
  await page.getByRole('option', { name: 'in_list' }).locator('span').click();
  await page.locator('input[name="Degree Status"]').click();
  await page.getByText('in_list▼').nth(4).click();
  await page.getByRole('option', { name: 'equals' }).locator('span').click();
  await page.locator('input[name="Degree Status"]').click();
  await page.getByRole('option', { name: 'Currently Enrolled' }).click();
  await page.getByText('What is your degree status?Condition*equals▼What is your degree status?').click();
  await page.locator('div').filter({ hasText: /^Condition\*equals▼What is your degree type\(full time, part time\)▼$/ }).getByLabel('Condition*').click();
  await page.getByRole('option', { name: 'in_list' }).click();
  await page.locator('input[name="Degree type"]').click();
  await page.getByText('Full Time on Site').click();
  await page.getByRole('option', { name: 'Part Time on Site' }).click();
  await page.getByText('equals').nth(2).click();
  await page.getByRole('option', { name: 'greater_than', exact: true }).click();
  await page.locator('div').filter({ hasText: /^Condition\*greater_than▼When is your Degree Start DateDay▼Month▼2025▼$/ }).locator('#customDateInput-year').click();
  await page.getByText('Month▼').first().click();
  await page.getByRole('option', { name: 'September' }).click();
  await page.locator('div').filter({ hasText: /^Day▼September▼2025▼$/ }).locator('#customDateInput-day').click();
  await page.getByText('1', { exact: true }).click();
  await page.locator('div').filter({ hasText: /^Condition\*equals▼When is your Degree End Date\?Day▼Month▼2025▼$/ }).getByLabel('Condition*').click();
  await page.getByText('less_than', { exact: true }).click();
  await page.locator('div').filter({ hasText: /^Day▼Month▼2025▼$/ }).locator('#customDateInput-year').click();
  await page.getByText('2027').click();
  await page.getByText('Month▼').click();
  await page.getByText('October').click();
  await page.getByText('Day').click();
  await page.getByRole('option', { name: '1', exact: true }).click();
  await page.getByRole('button', { name: 'Add Group Condition' }).click();
  await page.getByRole('button', { name: 'Tell us about yourself' }).click();
  await page.getByRole('button', { name: 'Remove eligibility form' }).click();
  await page.getByRole('button', { name: 'Care Responsiblity' }).click();
  await page.getByRole('combobox', { name: 'Do you have significant care' }).click();
  await page.getByRole('option', { name: 'Yes' }).click();
  await page.getByText('Create Eligibility Criteria Create Eligibility Criteria for the grantGrade for').click();
  await page.getByRole('button', { name: 'Save Eligibility' }).click();
  await page.getByRole('button', { name: 'Tell us about yourself' }).click();
  await page.getByText('Grade for the DegreeHonoursDegree StatusWhat is the Degree LevelDegree').click();
  await page.getByRole('button', { name: 'Financial Need' }).click();
  await page.getByRole('button', { name: 'Academic and Career Goals' }).click();
  await page.getByRole('button', { name: 'Save Questions' }).click();
  await page.getByRole('button', { name: 'Questions' }).click();
  await page.getByRole('button', { name: 'Create Custom Question' }).click();
  await page.getByRole('textbox', { name: 'Question Name *' }).click();
  await page.getByRole('button', { name: 'Close modal' }).click();
  await page.getByRole('button', { name: 'Selection Criteria' }).click();
  await page.getByRole('button', { name: 'Tell us about yourself' }).click();
  await page.getByRole('button', { name: 'Financial Need' }).click();
  await page.getByRole('button', { name: 'Academic and Career Goals' }).click();
  await page.getByRole('button', { name: 'Save Selection Criteria' }).click();
  await page.getByRole('button', { name: 'Make Public' }).click();
  await page.getByRole('button', { name: 'Make Program Public' }).click();
  await page.locator('div').filter({ hasText: /^New Grant Program for Test$/ }).click();
  await page.getByRole('link', { name: 'Organisation' }).click();
  await page.getByRole('button', { name: 'Description' }).click();
  await page.getByRole('button', { name: 'Staff' }).click();
  await page.getByRole('button', { name: 'Organisation Name' }).click();
  await page.getByRole('link', { name: 'My Profile' }).click();
  await page.getByRole('button', { name: 'Create Grant' }).click();
  await page.getByRole('button', { name: 'List Grants' }).click();
  await page.getByRole('button', { name: 'Review Application' }).click();
  await page.getByRole('combobox', { name: 'Select Grant Program *' }).click();
  await page.getByText('New Grant Program for Test').click();
  await page.getByText('New Grant Program for Test').click();
  await page.getByText('Next Grant Program').click();
  await page.getByText('Next Grant Program').click();
  await page.getByText('Community Cohesion Fund:').click();
  await page.getByRole('combobox', { name: 'Select Grant Program *' }).click();
  await page.getByRole('option', { name: 'The Horizon Innovators Grant' }).click();
  await page.getByText('The Horizon Innovators Grant').click();
  await page.getByRole('option', { name: 'Community Cohesion Fund:' }).click();
  await page.locator('div').filter({ hasText: /^Not Marked$/ }).click();
  await page.goto('http://localhost:5173/grant-management/review');
  await page.getByRole('combobox', { name: 'Select Grant Program *' }).click();
  await page.getByText('Community Cohesion Fund:').click();
  await page.locator('div').filter({ hasText: /^Not Marked$/ }).click();
  await page.locator('input[name="eval-6890a0d4b5a3b5404f4b0e85"]').click();
  await page.locator('input[name="eval-6890a0d4b5a3b5404f4b0e85"]').fill('79');
  await page.locator('input[name="eval-6890a0d4b5a3b5404f4b0e86"]').click();
  await page.locator('input[name="eval-6890a0d4b5a3b5404f4b0e86"]').fill('72');
  await page.locator('input[name="eval-6890a0d4b5a3b5404f4b0e87"]').click();
  await page.locator('input[name="eval-6890a0d4b5a3b5404f4b0e87"]').fill('60');
  await page.locator('input[name="eval-6890a0d4b5a3b5404f4b0e88"]').click();
  await page.locator('input[name="eval-6890a0d4b5a3b5404f4b0e88"]').fill('55');
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Save Evaluations' }).click();
  await page.getByRole('button', { name: 'Back to Applications' }).click();
  await page.getByRole('combobox', { name: 'Select Grant Program *' }).click();
  await page.getByText('Community Cohesion Fund:').click();
  await page.getByRole('button', { name: 'Select' }).click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Select' }).click();
  await page.getByText('Review Applications Review and manage grant applicationsSelect Grant Program*').click();
  await page.getByRole('button', { name: 'Messages' }).click();
  await page.getByRole('button', { name: '+  Create New Message' }).click();
  await page.getByRole('combobox', { name: 'Student *' }).click();
  await page.getByText('Kohei Oishi (Community').click();
  await page.getByRole('textbox', { name: 'Message' }).click();
  await page.getByRole('textbox', { name: 'Message' }).fill('Hi Kohei, thank you for applying to our grant program. i am happy to tell you that you are selected. ');
  await page.getByRole('button', { name: 'Send Message' }).click();
  await page.getByText('Name : Kohei OishiApplied for : Community Cohesion Fund: Local Arts &').click();
  await page.getByRole('button', { name: 'Sign Out' }).click();
});